Repository mysticalfoxie/GalaxyGobbles, pull requests merged in 2024-08, with the labels that each got.

#10 Add Animation Framework + Some starter Animations
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/Abstractions/Touchable.cs
  Assets/02_Scripts/Animations/Animation.cs
  Assets/02_Scripts/Animations/AnimationBuilder.cs
  Assets/02_Scripts/Animations/AnimationFunctions.cs
  Assets/02_Scripts/Animations/AnimationHandler.cs.meta
  Assets/02_Scripts/Animations/AnimatorBase.cs
  Assets/02_Scripts/Animations/AnimatorBase.cs.meta
  Assets/02_Scripts/Animations/ScalingAnimator.cs
  Assets/02_Scripts/Animations/ScalingAnimator.cs.meta
  Assets/02_Scripts/Animations/TouchAnimator.cs
  Assets/02_Scripts/Animations/TouchAnimator.cs.meta
  Assets/02_Scripts/Animations/TouchExpandAnimator.cs
  Assets/02_Scripts/Animations/TouchExpandAnimator.cs.meta
  Assets/02_Scripts/Animations/TouchShrinkAnimator.cs
  Assets/02_Scripts/Animations/TouchShrinkAnimator.cs.meta
  Assets/02_Scripts/Contracts/ITouchable.cs
  Assets/02_Scripts/Contracts/ITouchable.cs.meta
  Assets/02_Scripts/Enums/AnimationInterpolation.cs
  Assets/02_Scripts/Extensions/LinqExtensions.cs
  Assets/02_Scripts/Extensions/LinqExtensions.cs.meta
  Assets/02_Scripts/Extensions/VectorExtensions.cs
  Assets/02_Scripts/Gameplay/Character/KittyBot.cs
  Assets/02_Scripts/Gameplay/Character/MainCharacter.cs
  Assets/02_Scripts/Gameplay/Customers/CustomerStateRenderer.cs
  Assets/02_Scripts/Gameplay/Items/Item.cs
  Assets/02_Scripts/Gameplay/Items/ItemRenderer.cs
  Assets/02_Scripts/Gameplay/Tables/Chair.cs
  Assets/02_Scripts/Selection/TableSelectionMode.cs
  Assets/02_Scripts/Settings/GameSettings.cs
  Assets/02_Scripts/System/TouchAnimation.cs
  Assets/02_Scripts/System/TouchAnimation.cs.meta
  Assets/02_Scripts/System/TouchFeedback.cs
  Assets/02_Scripts/System/TouchHandler.cs
  Assets/02_Scripts/System/TouchInputSystem.cs
  Assets/02_Scripts/UI/Inventory.cs
  Assets/02_Scripts/UI/TrashCan.cs
  Assets/03_Prefabs/02_Objects/PRE_Counter Bar Area L.prefab
  Assets/03_Prefabs/02_Objects/PRE_Cutting Board.prefab
  Assets/03_Prefabs/02_Objects/PRE_Ingredient Bowl.prefab
  Assets/03_Prefabs/02_Objects/PRE_Noodle Bowl.prefab
  Assets/03_Prefabs/02_Objects/PRE_Noodle Pot.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Item.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Mesh_Chair.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Table (Horizontal).prefab
  Assets/03_Prefabs/02_Objects/PRE_Placemat.prefab
  Assets/03_Prefabs/02_Objects/PRE_Spoon_Chopsticks.prefab
  Assets/03_Prefabs/03_Character/PRE_CHAR_Customer.prefab
  Assets/04_Graphics/04_Sprites/04_UI/SP_Questionmark (New).png
  Assets/04_Graphics/04_Sprites/04_UI/SP_Questionmark (New).png.meta
  Assets/10_Miscellaneous/03_Settings/CFG_Game Settings.asset
Labels: ready for review

#17 Fix Level Button Scaling
  Assets/02_Scripts/UI/LevelButton.cs
Labels: bug, ready for review

#19 Fix a bug with the Sound Slider
  Assets/02_Scripts/UI/MainMenu.cs
Labels: ready for review

#13 Added Chantelle's meshes + Prefabs + new test scene
  Assets/01_Scenes/Development/0.1_Main Level_Sabi_AssetTest2.unity
  Assets/01_Scenes/Development/0.1_Main Level_Sabi_AssetTest2.unity.meta
  Assets/01_Scenes/Development/0.2_Main Level 2_Sabi_AssetTesting.unity
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Aloe_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Aloe_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Bamboo_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Bamboo_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_CherryTree.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_CherryTree.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Chopsticks_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Chopsticks_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Cup_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Cup_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Lantern_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Lantern_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Seat_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Seat_low.prefab.meta
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Table_low.prefab
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Table_low.prefab.meta
  Assets/04_Graphics/02_Textures/Materials/T_Wood Base Color_1.mat
  Assets/04_Graphics/02_Textures/Materials/T_Wood Base Color_1.mat.meta
  Assets/04_Graphics/03_Meshes/SM_Aloe_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Aloe_low2.fbx
  Assets/04_Graphics/03_Meshes/SM_Aloe_low2.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_Bamboo_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Bamboo_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_Cabinet_Drawers_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Cabinet_Drawers_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_CherryTree_low3.fbx
  Assets/04_Graphics/03_Meshes/SM_CherryTree_low3.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_Lantern_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Lantern_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_PipeBent_low.fbx
  Assets/04_Graphics/03_Meshes/SM_PipeBent_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_PipeConnector_low.fbx
  Assets/04_Graphics/03_Meshes/SM_PipeConnector_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_PipeMiddle_low.fbx
  Assets/04_Graphics/03_Meshes/SM_PipeMiddle_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_Pot_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Pot_low.fbx.meta
  Assets/04_Graphics/03_Meshes/SM_Seat_low.fbx
  Assets/04_Graphics/03_Meshes/SM_Seat_low.fbx.meta
Labels: work in progress

#20 Gameplay Bugfixes
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/Animations/TouchAnimator.cs
  Assets/02_Scripts/Gameplay/Customers/CustomerStateRenderer.cs
  Assets/02_Scripts/Gameplay/Machines/NoodlePot.cs
  Assets/02_Scripts/Gameplay/Tables/Table.cs
  Assets/02_Scripts/System/GlobalTimeline.cs
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Table (Horizontal).prefab
  Assets/03_Prefabs/03_Character/PRE_CHAR_Customer.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_PNL_Chat Bubble.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_PNL_Chat Bubble.prefab.meta
  Assets/09_Data/04_Sprites/Statuses/SP_Cleaning.asset
Labels: ready for review

#18 Fix Level Unlock
  Assets/02_Scripts/UI/LevelButton.cs
  Assets/02_Scripts/UI/LevelSelector.cs
Labels: bug, ready for review

#27 Chantelle design sprites
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Laser_Scanning_Clean_Tables.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Laser_Scanning_Clean_Tables.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Steam.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Steam.png.meta
  Assets/09_Data/04_Sprites/Food and Drinks/SP_Baby Bok Choy 02.asset
  Assets/09_Data/04_Sprites/Food and Drinks/SP_Eye Bubble Tea.asset
  Assets/09_Data/04_Sprites/Food and Drinks/SP_Eyes.asset
  Assets/09_Data/04_Sprites/Statuses/SP_Eating.asset
Labels: ready for review

#31 Adjust the Scoring System for the Assassination
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/Gameplay/Customers/Customer.cs
  Assets/02_Scripts/Models/LevelData.cs
  Assets/02_Scripts/Settings/GameSettings.cs
  Assets/09_Data/01_Levels/LVL_Level 03.asset
Labels: ready for review

#32 Edit Volumeslider
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/03_Prefabs/04_UI/PRE_UI.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_Slider.prefab
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: ready for review

#30 Edit Bottombar (progressbar etc)
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/03_Prefabs/04_UI/PRE_UI.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_Bottom Bar.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_Divider (Stars).prefab
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: ready for review

#34 Do some general fixes
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/Gameplay/Debug/SkipLevel.cs
  Assets/02_Scripts/Gameplay/Debug/SkipLevel.cs.meta
  Assets/02_Scripts/Settings/GameSettings.cs
  Assets/02_Scripts/System/CustomerHandler.cs
  Assets/02_Scripts/System/GlobalTimeline.cs
  Assets/02_Scripts/UI/Fader.cs
  Assets/02_Scripts/UI/MainMenu.cs
  Assets/03_Prefabs/04_UI/PRE_UI.prefab
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
Labels: ready for review

#36 Edit Pausemenu
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/UI/MainMenu.cs
  Assets/03_Prefabs/04_UI/PRE_UI.prefab
  Assets/03_Prefabs/04_UI/PRE_UI_BTN_Default.prefab
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: ready for review

#37 Add UI Sounds
  Assets/02_Scripts/Settings/AudioSettings.cs
  Assets/02_Scripts/UI/CreditsBook.cs
  Assets/02_Scripts/UI/HowtoplayScreen.cs
  Assets/02_Scripts/UI/LevelButton.cs
  Assets/02_Scripts/UI/MainMenu.cs
  Assets/02_Scripts/UI/ProgressBar.cs
  Assets/09_Data/07_Audio/SFX_Progress_StarsCombo_1.asset
  Assets/09_Data/07_Audio/SFX_Progress_StarsCombo_2.asset
  Assets/09_Data/07_Audio/SFX_Progress_StarsCombo_3.asset
  Assets/09_Data/07_Audio/SFX_UI_Back.asset
  Assets/09_Data/07_Audio/SFX_UI_Close.asset
  Assets/09_Data/07_Audio/SFX_UI_OpenPopUp.asset
  Assets/09_Data/07_Audio/SFX_UI_SelectItem.asset
  Assets/09_Data/07_Audio/SFX_UI_Stamp.asset
  Assets/09_Data/07_Audio/SFX_UI_StartGame.asset
  Assets/09_Data/07_Audio/SFX_UI_UnlockUpgrade.asset
  Assets/10_Miscellaneous/03_Settings/CFG_Audio Settings.asset
  Assets/10_Miscellaneous/03_Settings/CFG_Game Settings.asset
Labels: ready for review

#35 Star Fixing
  Assets/09_Data/01_Levels/LVL_Level 01.asset
  Assets/09_Data/01_Levels/LVL_Level 02.asset
  Assets/09_Data/01_Levels/LVL_Level 04.asset
  Assets/09_Data/01_Levels/LVL_Level 06.asset
  Assets/09_Data/01_Levels/LVL_Level 07.asset
  Assets/09_Data/01_Levels/LVL_Level 08.asset
Labels: ready for review

#38 Last changes before v1.0.0
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/02_Scripts/Gameplay/Tables/Table.cs
  Assets/02_Scripts/UI/MainMenu.cs
  Assets/03_Prefabs/02_Objects/PRE_OBJ_Table (Horizontal).prefab
  Assets/03_Prefabs/03_Character/PRE_CHAR_Customer.prefab
  Assets/07_3rdParty/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/09_Data/07_Audio/TRCK_InGameMusic_LevelFailed.asset
  Assets/09_Data/07_Audio/TRCK_InGameMusic_LevelSuccess.asset
  Assets/10_Miscellaneous/03_Settings/CFG_Game Settings.asset
Labels: ready for review

#39 Fix How to Play Images
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/03_Prefabs/04_UI/PRE_UI.prefab
Labels: ready for review

#40 Added sprite animations_
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Beam_old.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Beam_old.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_HUD_Sign.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_HUD_Sign.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Open_Closed_old.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Open_Closed_old.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Pink_Beaming.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Pink_Beaming.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Loop.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Loop.png.meta
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Steam_old.png
  Assets/04_Graphics/04_Sprites/04_UI/00_Sprite_Animations/SP_Smoke_Steam_old.png.meta
Labels: ready for review

#41 Blancing and Polishing
  Assets/01_Scenes/0.0_Main Menu.unity
  Assets/01_Scenes/0.1_Main Level.unity
  Assets/04_Graphics/04_Sprites/04_UI/SP_how_to_play_Kitty.png
  Assets/04_Graphics/04_Sprites/04_UI/SP_how_to_play_Kitty.png.meta
  Assets/09_Data/01_Levels/LVL_Level 05.asset
  Assets/09_Data/01_Levels/LVL_Level 06.asset
  Assets/09_Data/01_Levels/LVL_Level 07.asset
  Assets/09_Data/01_Levels/LVL_Level 08.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 03.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 04.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 05.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 06.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 07.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 08.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 09.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 10.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 11.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 12.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 13.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 14.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 15.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 16.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 17.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 18.asset
  Assets/09_Data/05_Customers/05_Level 05/LVL_05_Customer 18.asset.meta
  Assets/09_Data/05_Customers/06_Level 06/LVL_06_Customer 16.asset
  Assets/09_Data/05_Customers/08_Level 08/LVL_08_Customer 07.asset
  Assets/09_Data/05_Customers/08_Level 08/LVL_08_Customer 17.asset
  Assets/09_Data/05_Customers/08_Level 08/LVL_08_Customer 19.asset
  Assets/09_Data/05_Customers/08_Level 08/LVL_08_Customer 21.asset
  Assets/10_Miscellaneous/03_Settings/CFG_Game Settings.asset
Labels: ready for review
